"""create webhook intake tables

Revision ID: 53b58928fdb7
Revises:
Create Date: 2026-08-24 12:06:40.280381

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53b58928fdb7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), server_default="razorpay", nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("account_id", sa.String(length=128), nullable=True),
        sa.Column("provider_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "processing_status", sa.String(length=32), server_default="received", nullable=False
        ),
        sa.Column("delivery_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "first_received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "processing_status IN ('received', 'queued', 'processing', 'processed', 'failed')",
            name="ck_webhook_events_processing_status",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="uq_webhook_events_provider_event_id"
        ),
    )
    op.create_index(
        "ix_webhook_events_status_received",
        "webhook_events",
        ["processing_status", "first_received_at"],
        unique=False,
    )
    op.create_index(
        "ix_webhook_events_type_created",
        "webhook_events",
        ["event_type", "provider_created_at"],
        unique=False,
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("canonical_event_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=32), server_default="razorpay", nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=True),
        sa.Column("event_type", sa.String(length=128), nullable=True),
        sa.Column("raw_payload", sa.LargeBinary(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload_size_bytes", sa.Integer(), nullable=False),
        sa.Column("signature_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "signature_status", sa.String(length=16), server_default="missing", nullable=False
        ),
        sa.Column(
            "delivery_status", sa.String(length=16), server_default="received", nullable=False
        ),
        sa.Column("is_duplicate", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("rejection_reason", sa.String(length=255), nullable=True),
        sa.Column("response_status_code", sa.Integer(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_status IN ('received', 'accepted', 'duplicate', 'rejected', 'failed')",
            name="ck_webhook_deliveries_delivery_status",
        ),
        sa.CheckConstraint(
            "signature_status IN ('verified', 'invalid', 'missing')",
            name="ck_webhook_deliveries_signature_status",
        ),
        sa.CheckConstraint("payload_size_bytes >= 0", name="ck_webhook_deliveries_payload_size"),
        sa.CheckConstraint(
            "response_status_code IS NULL OR response_status_code BETWEEN 100 AND 599",
            name="ck_webhook_deliveries_response_status",
        ),
        sa.ForeignKeyConstraint(
            ["canonical_event_id"],
            ["webhook_events.id"],
            name=op.f("fk_webhook_deliveries_canonical_event_id_webhook_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_deliveries")),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_canonical_event_id"),
        "webhook_deliveries",
        ["canonical_event_id"],
        unique=False,
    )
    op.create_index(
        "ix_webhook_deliveries_event_received",
        "webhook_deliveries",
        ["provider_event_id", "received_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_webhook_deliveries_event_received", table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_canonical_event_id"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index("ix_webhook_events_type_created", table_name="webhook_events")
    op.drop_index("ix_webhook_events_status_received", table_name="webhook_events")
    op.drop_table("webhook_events")
    # ### end Alembic commands ###
