"""create transactional outbox

Revision ID: 81959b025796
Revises: 53b58928fdb7
Create Date: 2026-08-24 13:25:49.221407

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "81959b025796"
down_revision: str | Sequence[str] | None = "53b58928fdb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("webhook_event_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("broker_message_id", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'publishing', 'published', 'failed')",
            name="ck_outbox_messages_status",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_outbox_messages_attempt_count"),
        sa.ForeignKeyConstraint(
            ["webhook_event_id"],
            ["webhook_events.id"],
            name=op.f("fk_outbox_messages_webhook_event_id_webhook_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
        sa.UniqueConstraint(
            "topic", "webhook_event_id", name="uq_outbox_messages_topic_webhook_event_id"
        ),
    )
    op.create_index(
        "ix_outbox_messages_dispatch",
        "outbox_messages",
        ["status", "available_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_messages_webhook_event_id"),
        "outbox_messages",
        ["webhook_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_messages_webhook_event_id"), table_name="outbox_messages")
    op.drop_index("ix_outbox_messages_dispatch", table_name="outbox_messages")
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###
