"""create revenue incident persistence

Revision ID: bc977924af18
Revises: 50e60722ea61
Create Date: 2026-08-24 20:20:04.225668

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc977924af18"
down_revision: str | Sequence[str] | None = "50e60722ea61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revenue_incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("dimension_value", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_attempts", sa.Integer(), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("total_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("revenue_at_risk_minor", sa.BigInteger(), nullable=False),
        sa.Column("failure_rate", sa.Float(), nullable=False),
        sa.Column("baseline_failure_rate", sa.Float(), nullable=False),
        sa.Column("absolute_uplift", sa.Float(), nullable=False),
        sa.Column("rate_multiplier", sa.Float(), nullable=True),
        sa.Column("robust_z_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "(status IN ('resolved', 'dismissed') "
                "AND resolved_at IS NOT NULL) OR "
                "(status IN ('open', 'investigating', 'mitigating') "
                "AND resolved_at IS NULL)"
            ),
            name="ck_revenue_incidents_resolution",
        ),
        sa.CheckConstraint(
            "scope IN ('global', 'payment_method', 'error_signature')",
            name="ck_revenue_incidents_scope",
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name="ck_revenue_incidents_severity",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'investigating', 'mitigating', 'resolved', 'dismissed')",
            name="ck_revenue_incidents_status",
        ),
        sa.CheckConstraint(
            "baseline_failure_rate BETWEEN 0 AND 1", name="ck_revenue_incidents_baseline_rate"
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_revenue_incidents_confidence"),
        sa.CheckConstraint(
            "current_window_end > current_window_start", name="ck_revenue_incidents_window"
        ),
        sa.CheckConstraint(
            "failed_attempts >= 0 AND failed_attempts <= total_attempts",
            name="ck_revenue_incidents_failed_attempts",
        ),
        sa.CheckConstraint(
            "failure_rate BETWEEN 0 AND 1", name="ck_revenue_incidents_failure_rate"
        ),
        sa.CheckConstraint("occurrence_count >= 1", name="ck_revenue_incidents_occurrence_count"),
        sa.CheckConstraint(
            "revenue_at_risk_minor >= 0 AND revenue_at_risk_minor <= total_amount_minor",
            name="ck_revenue_incidents_revenue_at_risk",
        ),
        sa.CheckConstraint("total_amount_minor >= 0", name="ck_revenue_incidents_total_amount"),
        sa.CheckConstraint("total_attempts >= 0", name="ck_revenue_incidents_total_attempts"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revenue_incidents")),
    )
    op.create_index(
        "ix_revenue_incidents_active_queue",
        "revenue_incidents",
        ["status", "severity", "last_detected_at"],
        unique=False,
    )
    op.create_index(
        "ix_revenue_incidents_scope_detected",
        "revenue_incidents",
        ["scope", "dimension_value", "last_detected_at"],
        unique=False,
    )
    op.create_index(
        "uq_revenue_incidents_active_fingerprint",
        "revenue_incidents",
        ["fingerprint", "currency"],
        unique=True,
        postgresql_where=sa.text("status IN ('open', 'investigating', 'mitigating')"),
    )
    op.create_table(
        "incident_detection_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("detector_run_id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column(
            "detector_version", sa.String(length=32), server_default="robust-mad-v1", nullable=False
        ),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("dimension_value", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("baseline_window_count", sa.Integer(), nullable=False),
        sa.Column("total_attempts", sa.Integer(), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("total_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("revenue_at_risk_minor", sa.BigInteger(), nullable=False),
        sa.Column("failure_rate", sa.Float(), nullable=False),
        sa.Column("baseline_failure_rate", sa.Float(), nullable=True),
        sa.Column("mad_failure_rate", sa.Float(), nullable=True),
        sa.Column("absolute_uplift", sa.Float(), nullable=True),
        sa.Column("rate_multiplier", sa.Float(), nullable=True),
        sa.Column("robust_z_score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "(outcome = 'incident' "
                "AND severity IS NOT NULL "
                "AND incident_id IS NOT NULL) OR "
                "(outcome IN ('normal', 'insufficient_data') "
                "AND severity IS NULL)"
            ),
            name="ck_incident_observations_decision",
        ),
        sa.CheckConstraint(
            "outcome IN ('normal', 'insufficient_data', 'incident')",
            name="ck_incident_observations_outcome",
        ),
        sa.CheckConstraint(
            "scope IN ('global', 'payment_method', 'error_signature')",
            name="ck_incident_observations_scope",
        ),
        sa.CheckConstraint(
            "severity IS NULL OR severity IN ('low', 'medium', 'high', 'critical')",
            name="ck_incident_observations_severity",
        ),
        sa.CheckConstraint(
            "baseline_failure_rate IS NULL OR baseline_failure_rate BETWEEN 0 AND 1",
            name="ck_incident_observations_baseline_rate",
        ),
        sa.CheckConstraint(
            "baseline_window_count >= 0", name="ck_incident_observations_baseline_count"
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name="ck_incident_observations_confidence"
        ),
        sa.CheckConstraint(
            "failed_attempts >= 0 AND failed_attempts <= total_attempts",
            name="ck_incident_observations_failed_attempts",
        ),
        sa.CheckConstraint(
            "failure_rate BETWEEN 0 AND 1", name="ck_incident_observations_failure_rate"
        ),
        sa.CheckConstraint(
            "revenue_at_risk_minor >= 0 AND revenue_at_risk_minor <= total_amount_minor",
            name="ck_incident_observations_revenue_at_risk",
        ),
        sa.CheckConstraint("total_amount_minor >= 0", name="ck_incident_observations_total_amount"),
        sa.CheckConstraint("total_attempts >= 0", name="ck_incident_observations_total_attempts"),
        sa.CheckConstraint("window_end > window_start", name="ck_incident_observations_window"),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["revenue_incidents.id"],
            name=op.f("fk_incident_detection_observations_incident_id_revenue_incidents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_detection_observations")),
        sa.UniqueConstraint(
            "fingerprint",
            "currency",
            "window_start",
            "window_end",
            "detector_version",
            name="uq_incident_observations_window_version",
        ),
    )
    op.create_index(
        "ix_incident_observations_incident_detected",
        "incident_detection_observations",
        ["incident_id", "detected_at"],
        unique=False,
    )
    op.create_index(
        "ix_incident_observations_outcome_detected",
        "incident_detection_observations",
        ["outcome", "detected_at"],
        unique=False,
    )
    op.create_index(
        "ix_incident_observations_run_detected",
        "incident_detection_observations",
        ["detector_run_id", "detected_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_incident_observations_run_detected", table_name="incident_detection_observations"
    )
    op.drop_index(
        "ix_incident_observations_outcome_detected", table_name="incident_detection_observations"
    )
    op.drop_index(
        "ix_incident_observations_incident_detected", table_name="incident_detection_observations"
    )
    op.drop_table("incident_detection_observations")
    op.drop_index(
        "uq_revenue_incidents_active_fingerprint",
        table_name="revenue_incidents",
        postgresql_where=sa.text("status IN ('open', 'investigating', 'mitigating')"),
    )
    op.drop_index("ix_revenue_incidents_scope_detected", table_name="revenue_incidents")
    op.drop_index("ix_revenue_incidents_active_queue", table_name="revenue_incidents")
    op.drop_table("revenue_incidents")
    # ### end Alembic commands ###
