"""add recovery audit sequence

Revision ID: e0b722e32771
Revises: 8e539eb14149
Create Date: 2026-08-24 22:27:06.637712

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0b722e32771"
down_revision: str | Sequence[str] | None = "8e539eb14149"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recovery_audit_events", sa.Column("sequence_number", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(
        "uq_recovery_audit_events_case_sequence",
        "recovery_audit_events",
        ["recovery_case_id", "sequence_number"],
    )
    op.create_check_constraint(
        "ck_recovery_audit_events_sequence", "recovery_audit_events", "sequence_number >= 1"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_recovery_audit_events_sequence", "recovery_audit_events", type_="check")
    op.drop_constraint(
        "uq_recovery_audit_events_case_sequence", "recovery_audit_events", type_="unique"
    )
    op.drop_column("recovery_audit_events", "sequence_number")
    # ### end Alembic commands ###
